# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/leviyeo/Desktop/Programming_Files/iGPManagerTooleo/tool/python/gui/views/loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(240, 166)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.load_wheel = QtWidgets.QLabel(self.frame)
        self.load_wheel.setText("")
        self.load_wheel.setPixmap(QtGui.QPixmap("/home/leviyeo/Desktop/Programming_Files/iGPManagerTooleo/tool/python/gui/views/../images/loading.png"))
        self.load_wheel.setAlignment(QtCore.Qt.AlignCenter)
        self.load_wheel.setObjectName("load_wheel")
        self.verticalLayout.addWidget(self.load_wheel)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Startup"))
