# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/leviyeo/Windows/Users/Christian/Documents/Programming_Files/iGPManagerTooleo/src/python/gui/views/row.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(443, 386)
        self.horizontalWidget = QtWidgets.QWidget(Form)
        self.horizontalWidget.setGeometry(QtCore.QRect(50, 130, 361, 121))
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rowName = QtWidgets.QLabel(self.horizontalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rowName.sizePolicy().hasHeightForWidth())
        self.rowName.setSizePolicy(sizePolicy)
        self.rowName.setMaximumSize(QtCore.QSize(16777215, 200))
        self.rowName.setAlignment(QtCore.Qt.AlignCenter)
        self.rowName.setObjectName("rowName")
        self.horizontalLayout.addWidget(self.rowName)
        self.row_dropdown = QtWidgets.QLabel(self.horizontalWidget)
        self.row_dropdown.setMaximumSize(QtCore.QSize(100, 100))
        self.row_dropdown.setText("")
        self.row_dropdown.setPixmap(QtGui.QPixmap("/media/leviyeo/Windows/Users/Christian/Documents/Programming_Files/iGPManagerTooleo/src/python/gui/views/../images/avocarleo.png"))
        self.row_dropdown.setObjectName("row_dropdown")
        self.horizontalLayout.addWidget(self.row_dropdown)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.rowName.setText(_translate("Form", "TextLabel"))
